gantt
  title DemoSM_ForkJoinSimple
  dateFormat  YYYY-MM-DD
  axisFormat  %d/%m
  excludes    weekends

  section Tasks
  Start :t1, 2026-02-16, 1d
  A :t2, after t1, 1d
  B :t3, after t1, 1d
  End :t4, after t3, 1d
