gantt
  title DemoSM_ForkJoinSequence
  dateFormat  YYYY-MM-DD
  axisFormat  %d/%m
  excludes    weekends

  section Tasks
  Start :t1, 2026-02-16, 1d
  A :t2, after t1, 1d
  B :t3, after t1, 1d
  C :t4, after t3, 1d
  D :t5, after t4, 1d
  End :t6, after t5, 1d
